# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "jira-mcp"], chdir: "."
  end if OS.mac?

  version "0.7.3"

  on_macos do
    on_arm do
      sha256 "f93a3d27ba3290268b8a6d1b437f020b6c89db8a4a11b91cd2de0fbd392fd371"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ccf1063ffd666da571ca9b0a28e32855a9c2c582624ee584592ffd5cf99e924"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2040fbdcfb2141d43ab9ebed10d7c7cd4ca5b0f1d38eb4b9eb2ab17bcaf57da3"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e21d3d0010f23f1a3e4221943f466e0b9dbee9d768295f07a57907d5f1856fbb"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  # No zap stanza required
end
