# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "fd03c7b345374beee0a7a7be41ca9b866e27d554efa7b25c7699b199a541c689"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1e617521b53ff625889758641252438aa4ab4ffc4e7f69febc9f92deec4a2a9"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "50c7db071b7f53305f0f4ede7248f729eec0bd929db33150397b91588c43fdad"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef74dd059c55ee5e9260f7ffe5ebaf537ea0ade2b83d16b3121b366a298170d0"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required

end
