# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  version "0.4.2"

  on_macos do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
      sha256 "f9733ca5f256d8e6164727b9e1d6948e85c611b693c379c5705135e3eb53de99"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
      sha256 "586c2ae9564aa34efd798265b4320acd83f4ee85901e4daa83d8f0528df682b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
      sha256 "26deaee6f5b832556ba6e798108d9b581b7da1d628d2d9d0d0ebf836a8daab78"
    end
    on_arm do
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
      sha256 "7b81a5481e59085b9a01adb5209f66abd6fd2bcb0095e22c84e33a6442ffc30f"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required

end
